require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MobileCoder' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'

  target 'MobileCoderTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'MobileCoder-tvOS' do
  # Pods for MobileCoder-tvOS

  target 'MobileCoder-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
